include ../Makefile.inc

FILES=	default.css		\
	index.html		\
	pktgen.js		\
	dygraph-combined.js	\
	jquery-1.11.1.min.js

all:
clean:
cleandir:
depend:

install:
	${INSTALL} -d ${DESTDIR}${PREFIX}/share/ipgen/htdocs
	${INSTALL_DATA} ${FILES} ${DESTDIR}${PREFIX}/share/ipgen/htdocs
